kind: ReplicationController
apiVersion: v1
metadata:
  name: sb-instanceid-spark-worker
spec:
  replicas: 2
  selector:
    servicebroker: sb-instanceid-spark-worker
  template:
    metadata:
      labels:
        servicebroker: sb-instanceid-spark-worker
    spec:
      containers:
        - name: sb-instanceid-spark-worker
          env: 
            - name: SPARK_MASTER_SERVICE_HOST
              value: 172.30.76.11
          image: index.alauda.cn/asiainfoldp/docker-spark
          command: ["/start-worker"]
          ports:
            - containerPort: 8081
          resources:
            requests:
              cpu: 100m

