apiVersion: v1
kind: Route
metadata:
  name: sb-instanceid-spark-webui
spec:
  host: sb-instanceid-spark-master-webui-datafoundry-servicebroker.app-jd.dataos.io
  to:
    kind: Service
    name: sb-instanceid-smw